### ISSUE TITLE
Connecting with envars is broken

### ISSUE THREAD

**Issue by sebakerckhof** [monti-apm/monti-apm-agent#5] opened 2018-07-12 15:30 UTC
This commit: https://github.com/monti-apm/monti-apm-agent/commit/671980b02b0af0b319fb703e20c3fab20b4eb927#diff-fb7fc841fcf9873d846fbd8249e2e4e2

Breaks connecting with envars.

Basically Meteor sets the `APP_ID` envar to the value of what's in `.meteor/.id` (see https://github.com/meteor/meteor/blob/devel/tools/static-assets/server/boot.js#L38 and  https://github.com/meteor/meteor/blob/devel/tools/runners/run-app.js#L201 ).

Since https://github.com/monti-apm/monti-apm-agent/commit/671980b02b0af0b319fb703e20c3fab20b4eb927#diff-fb7fc841fcf9873d846fbd8249e2e4e2 adds https://github.com/monti-apm/monti-apm-agent/blob/master/lib/environment_variables.js#L1-L9 it now can use that `APP_ID` as the kadira app id, which breaks connection to monti apm of course. I think it's a very bad idea to allow non-prefixed envars anyway.

**Comment by hexsprite** [comment] 2018-07-13 05:49
ahh that explains why it didn't work for me ;)

**Comment by zodern** [comment] 2018-07-13 16:33
Thanks for finding the cause @sebakerckhof. It is fixed in version 2.32.2.

**Closed by zodern** 2018-07-13 16:33 UTC
Labels: bug
